server.port: 4960
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/Project
spring.datasource.username: root
spring.datasource.password: Rome2totalwar
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create

